### ISSUE TITLE
Limits not working

### ISSUE THREAD

**Issue by JohOply** [Hidendra/LWC#874]
Hi

I use LWC 4.5.0-SNAPSHOT (#931) and Spigot 1.7.10. (I use LWC since a long time)

Before the update to 4.5.0's version, limits worked perfectly. Since, the amount of protections do not increase when a player create a new protection, and players can create an infinity amount of protections :)

Could you fix it ?

Thanks in advance :)

**Comment by FuRiouSOne** [comment]
Not working on Build #938 on spigot 1.8 either.

**Comment by Fjordcraft** [comment]
Got the same issue as you FuRiouSOne, I use the same versions. Would be great to get this fixed as soon as possible.

**Comment by JohOply** [comment]
Hi !

Now i use Spigot 1.8.7-b534 and LWC 4.5.0-b931

In my config, when a chest is created, there is an auto protection. But these protections aren't added into /climits.

I think this is because of differenciation of "Protections" and "Chest protections":  http://i.imgur.com/mLg0jYI.png

I hope you could fix it.

Thanks in advance

**Comment by JohOply** [comment]
I have found the problem : 
- "auto private" uses UUID (not count in limits)
- "private" uses username (count in limits)

**Comment by JohOply** [comment]
Fixed with EntityLWC https://www.spigotmc.org/resources/lwc-unofficial-entity-locking.2162/updates
