### ISSUE TITLE
Double Chests

### ISSUE THREAD

**Issue by IrParadox** [Hidendra/LWC#895]
Double chests are still causing an error for players to break their own chests. They can break the left side but not he right side.

**Comment by Chevels** [comment]
We have exactly the same problem for 4 days. In addition players can not destroy ender-chest.
I deleted the file lwc.db to deliver a backup built in six days, but the problem came back a few hours later.
This is very annoying and we are helpless: /

**Comment by Chevels** [comment]
Sorry, I just found where does this concern. LWC conflicts with the new version of the plugin Phatloots (4.0.0). In handing Phatloots 3.8.1, everything is in order.
The author of Phatloots 4.0.0 fixed a bug with double-chest and I think this is the point that conflicts with LWC.

**Comment by IrParadox** [comment]
This issue is not in LWC. It is in PhatLoots. This has also been confirmed by the PhatLoots author. Closing this ticket.
