### ISSUE TITLE
/cremoveall is broken.

### ISSUE THREAD

**Issue by andrewkm** [Hidendra/LWC#905]
/cremoveall is broken.

Using http://ci.griefcraft.com/job/LWC-testing-fast-uuid-conversion/4/

http://i.imgur.com/FYMxs8w.png

Simply doesn't remove any protections. Limits stay the same, and protections stay there.

**Comment by HeroCC** [comment]
PR #902 seems to fix this problem

**Comment by andrewkm** [comment]
That PR does not fix this issue as it causes incredible lag. We will work on a proper fix in the near future and PR one. Has been reverted: https://github.com/Hidendra/LWC/commit/71811e6fe9256e27787084b54158baa926b65a7a
