### ISSUE TITLE
External MySQL storage

### ISSUE THREAD

**Issue by frizzbee30** [Hidendra/LWC#907]
Hi, I'm just wondering if MySQL is only available for local databases. I have tried 2 or 3 times to migrate form SQLite to MySQL. The plugin populates the remote host tables effectively using the command. However as soon as storage is then changed on completion from sqlite to mysql ,server restarted, it gives an error of conversion from sqlite to mysql needed and stops. Is there something I am missing from the path, as currently I leave this to the local sqlite db since the external host IP is already populated. I've never seen a requirement to add a path in for an external host in MySQL configurations before. Thanks

**Comment by saturnux** [comment]
in core.yml you have set : traped_chest, but you can't do

**Comment by frizzbee30** [comment]
Hi, are you saying that is why the db wont convert?

**Comment by saturnux** [comment]
i dont have the error, but if your db is too big, or contain some error, the conversion stop.
i have some problem with migration form SQLite to MySQL, but at this time some item make error in history row.
if you have not cleanup the batabase do that: /lwc admin cleanup (it remove old  or unused protections)
if you have deletes or removed word, but nor removed old protection a remove of all protection of the world is possible.

**Comment by frizzbee30** [comment]
Thanks I'll try the cleanup in test :)

**Comment by frizzbee30** [comment]
now outdated/no longer maintained
