### ISSUE TITLE
Bypass Locked Gates with Pressure Plates

### ISSUE THREAD

**Issue by JamieSinn** [Hidendra/LWC#918]
http://www.ecocitycraft.com/forum/threads/bug-report-bypassing-locked-gates.130393/
```
Minecraft Username: huntmeister97

Disclaimer: I did mention this awhile back about the gates and never got an explanation. I have also tried turning on /credstone and turning it off

Brief Description:
A pressure plate will bypass a locked gate allowing you to enter the fenced area

Instructions:
1. Place a pressure plate in front of the Gate
2. Stand on pressure plate and bam you are in


How many times did you recreate this bug?:
not sure the amount but it was over 15 times if in fact this is a bug. I had @EMD3000 test to see if he could place a pressure plate in front of my locked gate

Result:
Emd placed the pressure plate in front of my locked gate and then stand on said Pressure plate and get into an area that was restricted

Expected Result:
The pressure plate should not open the gate

Evidence:
will provide if needed but they basically just show that I have the gate locked and that I tried /credstone on
```

**Comment by PgBiel** [comment]
Is that "gate" a plugin or something?

**Comment by Walkman100** [comment]
@PgBiel probably a fence gate

**Comment by JamieSinn** [comment]
Fence gate = gate
My apologies

**Comment by JohOply** [comment]
I have this problem ! Redstone could open gates even if redstone is disabled for it !

Could you fix it please ?

**Comment by baba43** [comment]
No updates on this?

**Comment by JohOply** [comment]
Use that, it is a LWC-improved : https://www.spigotmc.org/resources/lwc-unofficial-entity-locking.2162/updates

I don't know if issue is fixed

**Comment by JamieSinn** [comment]
I'll submit a PR to fix this sometime in the future.

**Comment by baba43** [comment]
Why do we close tickets that are still open?

Maybe someone else will find time to fix it :-)

**Comment by JamieSinn** [comment]
Because it's not something that will be fixed any time soon, and there was already a solution posted

**Comment by baba43** [comment]
Well but it is still an issue.. and I would not say that suggesting alternative plugins is a solution.

But nvm.
