### ISSUE TITLE
CRITICAL BUG: Open ANY CHEST with flint and steel

### ISSUE THREAD

**Issue by ghost** [Hidendra/LWC#973]
You can open any locked chest or any locked items with having flint and steel in your hand

**Comment by trainphreak** [comment]
Minecraft version? LWC version? What permission nodes did you have at the time?

**Comment by ghost** [comment]
Minecraft version is 1.12.2, LWC version is 1.9.4. Permission nodes are normal, I gave them ability to lock, and that's it. they can't open anything without the flintandsteel.

**Comment by RawrUniversal** [comment]
I need evidence.
I tested this and I can't open a locked chest with a flint and steel.

**Comment by Dragoboss** [comment]
Updated this here with video:
https://github.com/megoesrawr/Modern-LWC/issues/116

**Comment by ghost** [comment]
Apparently another plugin is causing the problem. the plugin is called Wormhole if anyone knew.
